@echo off
:: ============================================================================
:: KILAT Context Menu - One-Click Installer
:: ============================================================================

echo ============================================================================
echo 🚀 KILAT Context Menu Installer
echo ============================================================================
echo.

:: Check admin privileges
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo [INFO] Requesting administrator privileges...
    powershell -Command "Start-Process cmd -ArgumentList '/c %~f0' -Verb RunAs"
    exit /b
)

:: Get script directory
set "SCRIPT_DIR=%~dp0"

echo Creating registry file...

:: Create registry file with correct paths
(
echo Windows Registry Editor Version 5.00
echo.
echo ; KILAT Context Menu - Generated by installer
echo.
echo [HKEY_CLASSES_ROOT\Directory\Background\shell\KILAT]
echo @="Run KILAT Here"
echo "Icon"="python.exe"
echo "Position"="bottom"
echo.
echo [HKEY_CLASSES_ROOT\Directory\Background\shell\KILAT\command]
echo @="\"%SCRIPT_DIR%run_kilat_here.bat\" \"%%V\""
echo.
echo [HKEY_CLASSES_ROOT\Directory\shell\KILAT]
echo @="Run KILAT Here"
echo "Icon"="python.exe"
echo "Position"="bottom"
echo.
echo [HKEY_CLASSES_ROOT\Directory\shell\KILAT\command]
echo @="\"%SCRIPT_DIR%run_kilat_here.bat\" \"%%V\""
) > "%SCRIPT_DIR%kilat_context.reg"

:: Import registry
echo Importing registry...
regedit /s "%SCRIPT_DIR%kilat_context.reg"

if %errorlevel% equ 0 (
    echo.
    echo ============================================================================
    echo ✅ SUCCESS! Context menu installed!
    echo ============================================================================
    echo.
    echo You can now:
    echo   1. Right-click in any folder ^→ "Run KILAT Here"
    echo   2. Right-click on a folder ^→ "Run KILAT Here"
    echo.
    echo To uninstall, run: remove-context-menu.bat
    echo.
    echo NOTE: If menu doesn't appear, restart Windows Explorer or log out/in
    echo.
    pause
) else (
    echo.
    echo ❌ FAILED! Please run as administrator.
    echo.
    pause
)

:: Cleanup temp registry file
del /q "%SCRIPT_DIR%kilat_context.reg" 2>nul
